# Generated by Django 5.0.1 on 2024-03-04 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='thesis_app__publish_e9d7e3_idx',
            old_name='blogsite_po_publish_ab442f_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
