# Generated by Django 5.0.1 on 2024-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0002_rename_blogsite_po_publish_ab442f_idx_thesis_app__publish_e9d7e3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
